# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: ''

menu:
- {name: 'CV', url: 'cv'}
- {name: 'Projects', url: 'projects'}
- {name: 'Resources', url: 'resources'}
# - {name: 'Interesting Facts',  url: 'facts'}
# - {name: 'Learning Resources', url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
# - {name: 'About',              url: 'about'}
# - {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link:    'https://github.com/moibernabeu/'}
- {icon: 'envelope', link:   'mailto:moises.bernabeu@bsc.es'}
- {icon: 'info-circle', link: 'https://orcid.org/0000-0002-0498-5957'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'